version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src/Swiss.FCh.Cube.RawData"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps): "
  - package-ecosystem: "nuget"
    directory: "/src/Swiss.FCh.Cube.RawData.Tests"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps): "
  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`
    # You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps): "
